[package]
name = "rsa_rust"
version = "0.1.0"
authors = ["chronal"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
num = {version = "0.4.0", features = ["rand"]}
rayon = "1.7.0"
rand = "0.8.5"